### PR TITLE
feat(api): package `pyowm` for easy usage of API

### PR DESCRIPTION
**Pull request by im-coder-lg**
~We need to test if it is compatible with packaging into files, i.e. if it would make the files heavy, which I will.~

### Tasks

- [x] Add `pyowm`
- [x] Use the data from it for returning temperature and status
- [x] Add the remaining data from the API and the `pyowm` module
- [ ] Try to make the label dynamic for usage(later PRs)
- [x] Add city name on top of `searchbar`(this PR
- [x] Make sure the city name comes with the country code(ez) (later PRs)

***Please, do not change anything.***

***Note to self***: Go to [Gitpod](https://gitpod.io) and open your instance to code. **Do not forget.**

Edit(7 Aug 2023): Video proof on Zorin OS 16.3 Core

https://github.com/Futura-Py/weather/assets/76845820/68ee54ac-6218-4ade-b4b7-9f83ff6c06c5

---
I will have to add the other data, which I will do slowly. @Moosems can we make the label extend dynamically? That way, when the app launches, it would look small, but it will automatically enlarge upon searching for a city. We have to expand the `row` limit, maybe by incrementing with 1 when the search query is received... Your idea?

### CODE REVIEW

**Comment by sumeshir26** [comment]
@im-coder-lg Imo the UI is a bit plain rn, and it needs a bit of improvements... Any ideas anyone?

**Comment by im-coder-lg** [comment]
We'll add Sun Valley after this PR. I wanted to start the repo this way, focusing on the UI in the end, since it would be cumbersome to manage.

**Comment by im-coder-lg** [comment]
Alright, it's night for me!

the-flash-salute

**Comment by Moosems** [comment]
What is pyowm?

**Comment by Moosems** [comment]
Yes, I can make it dynamically expand ;). Permission to mess around with the PR?

**Comment by Moosems** [comment]
My idea:

It by default uses the minimum space, upon button press it updates the name, clears the entry, adds the loading bar, and expands the app to the proper size, and then as the data comes in and is processed the loading bar disappears and shows everything.

**Comment by Moosems** [comment]
> We'll add Sun Valley after this PR. I wanted to start the repo this way, focusing on the UI in the end, since it would be cumbersome to manage.

*Screams in lag.*

**Comment by Moosems** [comment]
> I think you can try replacing it with Sun Valley slowly to see how it might turn out. And we need an icon. Get some ideas, and try creating it like with TimerX, that was perfect, and I can bet my Flash GIFs that you will make the best Weather icon.
> 
> I'll try looking into other images to get some ideas, which I will post in a discussion soon.

My issue is the fact that it's either dark or light mode. I, though it's an unpopular opinion, prefer light mode.

**Comment by im-coder-lg** [comment]
Well, let's integrate a settings menu with the Sun Valley UI so that people can adjust the app to their choice+use their API if they want to.

**Comment by im-coder-lg** [comment]
> What is pyowm?

A famous module just for OWM. It simplifies the API usage, though sometimes either could be inaccurate, as I have noticed at times.

**Comment by Moosems** [comment]
Our system never had any issues so why swap over?

**Comment by im-coder-lg** [comment]
> I could add a loading bar as it retrieves the info :D.

Yeah, once we are done with this PR, we will do the loading bar. Maybe we get a light and dark variant to support both light mode and dark mode.

> Yes, I can make it dynamically expand ;). Permission to mess around with the PR?

Unfortunately not now. Let me finish the changes and then you can add the dynamic expansion. If I am not wrong, you will have to add an increment to the values when a city is searched for, right? Tell me if I am right. And also, can we add the city name on top of the search bar? I'll take it from the API request or PyOWM and we shall see..

> My idea:

It by default uses the minimum space, upon button press it updates the name, clears the entry, adds the loading bar, and expands the app to the proper size, and then as the data comes in and is processed the loading bar disappears and shows everything.

🤔
Let's try that, but for the loading bar, can we keep it in minimum space till the data is received? Then we can expand the window size. Also, sometimes when a request timeout occurs via PyOWM, we have to update the status label(where we can put loading bar and take it as a double meaning in our method) to show "Request timeout. Please try again" or a similar message/pop-up(which I prefer).


> > We'll add Sun Valley after this PR. I wanted to start the repo this way, focusing on the UI in the end, since it would be cumbersome to manage.
> 
> *Screams in lag.*

Bro why?


> My issue is the fact that it's either dark or light mode. I, though it's an unpopular opinion, prefer light mode.

Well, I prefer it before sunset, so we shall add both+system theme :)

> Our system never had any issues so why swap over?

I don't know whether I told this, but I tested OWM on a Colab instance, and I used PyOWM for getting some of the data. Unlike the API, PyOWM processes the data for immediate use, so we wouldn't have to do the math we used to do so. Better in my opinion.

**Comment by im-coder-lg** [comment]
Anything else to add, guys? Till now, I added:

- temperature(minimum, maximum and current)
- status of weather, which we can also use as the status label for the loading bar
- humidity
- pressure
- visibility
- wind speed

We need to make them modifiable, which we will do in later PRs. Anything I missed?

**Comment by im-coder-lg** [comment]
Oh, I forgot about the city name above the search bar. That's easy. I'll add it later. I need some time for managing the school work.

**Comment by im-coder-lg** [comment]
/ping @Moosems requesting a review from you! Check when free, artifacts are at latest action run :)

**Comment by sumeshir26** [comment]
@im-coder-lg I just made a quick logo, feedback please!
Futura Weather

**Comment by im-coder-lg** [comment]
yeah!

**Comment by im-coder-lg** [comment]
@Moosems my changes are done here. You can add the dynamic scaling in this PR or another one(which can be preferred for neatness).
Now, I added a label for the city so that when you search for a city, the actual name and country code appears on the label. For example, it is known in India that the city Bengaluru is usually referred to as Bangalore, just like that, and trust me, I know it. If I were to search either of the names for the same city, then the city name will still remain Bengaluru, since I took the name directly from the API. Neat trick, right?

Now, you can change the UI whichever way you want. I saw you mention that upon searching, the entry will be erased. In that case, make sure that there is a label for the city name, so that people would know the city name even after the entry is cleared. And make it a bit bigger in terms of font. Also, if you can, can you bind the Return/Enter key to the Search button? I tried, it didn't work, but I think if you do so, it might. Anyway, again, it is night.

the-flash-salute

**Comment by Moosems** [comment]
I'll make a branch off this PR and make my changes there.

**Comment by sumeshir26** [comment]
@im-coder-lg I wont be able to review, you can go ahead and merge.

**Comment by Moosems** [comment]
Hadn't started on it until your changes were done. Will begin work tomorrow.

**Comment by im-coder-lg** [comment]
@Moosems I added two more changes to this PR, it is related to the Code Formatting workflow, which I just fixed. I just wanted to update you. I expect to be done with this by now, but I'll go through the code to find some errors that need to be refactored.

**Comment by im-coder-lg** [comment]
Does anybody want to use the Wiki page in GitHub? I'd like to start with a table-of-contents, with steps for coding and pushing the PRs here if we do need it... Do we need it?

**Comment by Moosems** [comment]
> Yep, that's the last one. @Moosems are the changes ready or are you working on them? Maybe we could merge this, and then add the dynamic scaling, but what do you think we can do?

Merge this and then I add the UI updates as a separate PR.

**Comment by im-coder-lg** [comment]
Merging this PR!

**Pull request merged**
